[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# 友好短链：/i/abc123 -> /i.html?id=abc123
[[redirects]]
  from = "/i/:id"
  to   = "/i.html?id=:id"
  status = 200

# Function 简短别名
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
